/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.itenas.zoo.repository;

import java.awt.HeadlessException;
import java.text.DecimalFormat;
import java.util.List;
import org.itenas.zoo.model.Tiket;
import org.itenas.zoo.model.User;
import org.itenas.zoo.services.CrudService;
import org.itenas.zoo.utils.ConnectionManager;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class ViewFormTiket extends javax.swing.JFrame {

    private CrudService<T> tiketCrudService;
    private Tiket tiket;
    private final User user;
    private static final DecimalFormat df = new DecimalFormat("#,###.00");
    /**
     * Creates new form ViewFormTiket
     * @param user
     */
    public ViewFormTiket(org.itenas.zoo.model.User user) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.user = user;
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        text_id = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_kelola_tiket = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        text_namaAcara = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        text_Harga_Tiket = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        text_tanggal = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        combo_kategori_tiket = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        text_zona_tiket = new javax.swing.JTextField();
        button_create = new javax.swing.JButton();
        button_Update = new javax.swing.JButton();
        button_delete = new javax.swing.JButton();
        button_clear = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        text_search = new javax.swing.JTextField();
        button_search = new javax.swing.JButton();
        button_refresh = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menu_item_exit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(102, 255, 0));
        jPanel2.setForeground(new java.awt.Color(178, 2, 56));

        jPanel3.setBackground(new java.awt.Color(255, 255, 102));
        jPanel3.setForeground(new java.awt.Color(3, 159, 190));

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("KELOLA TIKET");

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\TubesOOP\\Sikebi\\Sikebi\\src\\main\\java\\org\\itenas\\zoo\\repository\\image\\7027123.png")); // NOI18N
        jLabel9.setText("jLabel7");

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\TubesOOP\\Sikebi\\Sikebi\\src\\main\\java\\org\\itenas\\zoo\\repository\\image\\4669585.png")); // NOI18N
        jLabel10.setText("jLabel4");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addGap(53, 53, 53)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("kode Tiket");

        text_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_idActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(61, 61, 61)
                .addComponent(text_id, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(text_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(0, 153, 153));

        tabel_kelola_tiket.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tabel_kelola_tiket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "kode", "NamaAcara", "harga", "tanggal", "jumlahTiket", "kategori", "zona"
            }
        ));
        tabel_kelola_tiket.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabel_kelola_tiket.setGridColor(new java.awt.Color(3, 159, 190));
        tabel_kelola_tiket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_kelola_tiketMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_kelola_tiket);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama Acara");

        text_namaAcara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_namaAcaraActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Harga Tiket");

        text_Harga_Tiket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_Harga_TiketActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tanggal Acara");

        text_tanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_tanggalActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Kategori Tiket");

        combo_kategori_tiket.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VIP", "Reguler", "Ekonomi" }));
        combo_kategori_tiket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_kategori_tiketActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("zona Tiket");

        text_zona_tiket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_zona_tiketActionPerformed(evt);
            }
        });

        button_create.setBackground(new java.awt.Color(232, 210, 29));
        button_create.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        button_create.setForeground(new java.awt.Color(255, 255, 255));
        button_create.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\idea.png")); // NOI18N
        button_create.setText("CREATE");
        button_create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_createActionPerformed(evt);
            }
        });

        button_Update.setBackground(new java.awt.Color(232, 210, 29));
        button_Update.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        button_Update.setForeground(new java.awt.Color(255, 255, 255));
        button_Update.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\updated.png")); // NOI18N
        button_Update.setText("UPDATE");
        button_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_UpdateActionPerformed(evt);
            }
        });

        button_delete.setBackground(new java.awt.Color(232, 210, 29));
        button_delete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        button_delete.setForeground(new java.awt.Color(255, 255, 255));
        button_delete.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\delete (1).png")); // NOI18N
        button_delete.setText("DELETE");
        button_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_deleteActionPerformed(evt);
            }
        });

        button_clear.setBackground(new java.awt.Color(232, 210, 29));
        button_clear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        button_clear.setForeground(new java.awt.Color(255, 255, 255));
        button_clear.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\cleaning.png")); // NOI18N
        button_clear.setText("CLEAR");
        button_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_clearActionPerformed(evt);
            }
        });

        jPanel7.setBackground(new java.awt.Color(102, 255, 0));
        jPanel7.setForeground(new java.awt.Color(178, 2, 56));

        text_search.setForeground(new java.awt.Color(102, 102, 102));
        text_search.setText("Search by code");
        text_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                text_searchMouseClicked(evt);
            }
        });
        text_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_searchActionPerformed(evt);
            }
        });

        button_search.setBackground(new java.awt.Color(255, 255, 255));
        button_search.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\web.png")); // NOI18N
        button_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_searchActionPerformed(evt);
            }
        });

        button_refresh.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\refresh.png")); // NOI18N
        button_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_refreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(text_search, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(button_search, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(button_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(text_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_search, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(button_create, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(button_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(button_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(button_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                                        .addComponent(text_namaAcara, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(32, 32, 32)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(text_Harga_Tiket, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                            .addComponent(text_tanggal))
                                        .addGap(65, 65, 65)))
                                .addGap(95, 95, 95)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(combo_kategori_tiket, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(text_zona_tiket, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(156, 156, 156)
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(text_namaAcara, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_Harga_Tiket, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(combo_kategori_tiket, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(text_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_zona_tiket, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(29, 29, 29)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(button_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(button_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(button_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(button_create, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenu1.setText("menu");

        menu_item_exit.setText("Exit");
        menu_item_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_exitActionPerformed(evt);
            }
        });
        jMenu1.add(menu_item_exit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void text_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_idActionPerformed

    private void tabel_kelola_tiketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_kelola_tiketMouseClicked
        String id, nama_acara, kategori_tiket;
        double hargatiket, hibahPenelitian;
        int pengalaman;

        int row = tabel_kelola_tiket.getSelectedRow();
        String gajiPokokStr = tabel_kelola_tiket.getValueAt(row, 2).toString().replace(",", "");
        String hibahPenelitianStr = tabel_kelola_tiket.getValueAt(row, 5).toString().replace(",", "");

        id = tabel_kelola_tiket.getValueAt(row, 0).toString();
        nama_acara = tabel_kelola_tiket.getValueAt(row, 1).toString();
        hargatiket = Double.parseDouble(gajiPokokStr);
        pengalaman = Integer.parseInt(tabel_kelola_tiket.getValueAt(row, 3).toString());
        kategori_tiket = tabel_kelola_tiket.getValueAt(row, 4).toString();
        hibahPenelitian = Double.parseDouble(hibahPenelitianStr);

        text_id.setText(id);
        text_id.setEnabled(false);
        text_namaAcara.setText(nama_acara);
        text_Harga_Tiket.setText(String.valueOf(df.format(hargatiket)));
        text_tanggal.setText(String.valueOf(pengalaman));
        combo_kategori_tiket.setSelectedItem(kategori_tiket);
        text_zona_tiket.setText(String.valueOf(df.format(hibahPenelitian)));
    }//GEN-LAST:event_tabel_kelola_tiketMouseClicked

    private void text_namaAcaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_namaAcaraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_namaAcaraActionPerformed

    private void text_tanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_tanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_tanggalActionPerformed

    private void button_createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_createActionPerformed
        // TODO add your handling code here:
        try {
        // Validasi input data
        if (text_id.getText().trim().isEmpty()
            || text_namaAcara.getText().trim().isEmpty()
            || text_Harga_Tiket.getText().trim().isEmpty()
            || text_tanggal.getText().trim().isEmpty()
            || combo_kategori_tiket.getSelectedItem() == null
            || text_zona_tiket.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua field harus diisi!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Parsing input data dengan aman
        String id = text_id.getText().trim();
        String namaAcara = text_namaAcara.getText().trim();
        double hargaTiket = Double.parseDouble(text_Harga_Tiket.getText().trim());
        String tanggalAcara = text_tanggal.getText().trim();
        String kategoriTiket = combo_kategori_tiket.getSelectedItem().toString();
        String zonaTiket = text_zona_tiket.getText().trim();

        // Set data ke objek tiket (contoh data simulasi)
        tiket = new Tiket();
        tiket.setId(id); // Mengatur ID Tiket
        tiket.setNamaAcara(namaAcara); // Mengatur Nama Acara
        tiket.setHarga(hargaTiket); // Harga Tiket disesuaikan dengan variabel gajiPokok
        tiket.setTanggal(tanggalAcara); // Tanggal Acara (diasumsikan sebagai String)
        tiket.setKategori(kategoriTiket); // Mengatur Kategori Tiket
        tiket.setZona(zonaTiket); // Zona Tiket

        // Simpan data
        tiketCrudService.create(tiket);
        JOptionPane.showMessageDialog(this, "Data berhasil disimpan!", "Success", JOptionPane.INFORMATION_MESSAGE);

        // Refresh tabel dan kosongkan input field
        loadData();
        emptyField();
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Format angka tidak valid! Periksa input Harga Tiket atau Zona Tiket.", "Error", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_button_createActionPerformed

    private void button_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_UpdateActionPerformed
        // Inisialisasi objek dan service yang diperlukan
        tiketCrudService = new TiketCrudServiceDbImpl(new ConnectionManager());
        
        try {
            // Validasi input data
            if (text_id.getText().trim().isEmpty()
                    || text_namaAcara.getText().trim().isEmpty()
                    || text_Harga_Tiket.getText().trim().isEmpty()
                    || text_tanggal.getText().trim().isEmpty()
                    || combo_kategori_tiket.getSelectedItem() == null
                    || text_zona_tiket.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Semua field harus diisi!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Ambil data dari input form
            String id = text_id.getText().trim();
            String namaAcara = text_namaAcara.getText().trim();
            String hargaTiketStr = text_Harga_Tiket.getText().replace(",", "");
            double hargaTiket = Double.parseDouble(hargaTiketStr.trim());
            String tanggalAcara = text_tanggal.getText().trim();
            String kategoriTiket = combo_kategori_tiket.getSelectedItem().toString();
            String zonaTiket = text_zona_tiket.getText().trim();

            // Set data ke objek tiket
            Tiket tiket = new Tiket();
            tiket.setId(id);
            tiket.setNamaAcara(namaAcara);
            tiket.setHarga(hargaTiket);
            tiket.setTanggal(tanggalAcara);
            tiket.setKategori(kategoriTiket);
            tiket.setZona(zonaTiket);

            // Lakukan update data
            tiketCrudService.update(id, tiket);
            JOptionPane.showMessageDialog(this, "Data Tiket berhasil diperbarui!", "Success", JOptionPane.INFORMATION_MESSAGE);
            loadData();
            emptyField();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Format angka tidak valid! Periksa kembali input Harga Tiket.", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_button_UpdateActionPerformed

    private void button_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_deleteActionPerformed
        // Inisialisasi service
        tiketCrudService = new TiketCrudServiceDbImpl(new ConnectionManager());

        // Ambil NIP dari input
        String kode = text_id.getText().trim();

        // Validasi apakah NIP kosong
        if (kode.isEmpty()) {
            JOptionPane.showMessageDialog(this, "kode harus diisi sebelum menghapus data!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Konfirmasi penghapusan data
        int dialogResult = JOptionPane.showConfirmDialog(this, "Are you sure to delete it?", "Warning", JOptionPane.YES_NO_OPTION);
        if (dialogResult == JOptionPane.YES_OPTION) {
            // Hapus data dan cek keberhasilannya
            boolean isDeleted = tiketCrudService.delete(kode);
            if (isDeleted) {
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus!", "Success", JOptionPane.INFORMATION_MESSAGE);
                loadData(); // Refresh tabel
                emptyField(); // Kosongkan input field
            } else {
                JOptionPane.showMessageDialog(this, "Gagal menghapus data. Periksa kembali kode!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_button_deleteActionPerformed

    private void button_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_clearActionPerformed
        emptyField();
    }//GEN-LAST:event_button_clearActionPerformed

    private void text_searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_searchMouseClicked
        text_search.setText("");
    }//GEN-LAST:event_text_searchMouseClicked

    private void text_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_searchActionPerformed

    private void button_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_searchActionPerformed
         String id = text_search.getText().trim();

    if (id.isEmpty()) {
        JOptionPane.showMessageDialog(this, "ID tidak boleh kosong!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Inisialisasi service
    CrudService CrudService = new TiketCrudServiceDbImpl(new ConnectionManager());
    T tiket = tiketCrudService.findOne(id);

    if (tiket != null) {
        // Tampilkan data ke tabel
        DefaultTableModel tableModel = (DefaultTableModel) tabel_kelola_tiket.getModel();
        tableModel.setRowCount(0); // Hapus data lama

        Object[] rowData = {
            tiket.getId(),
            tiket.getNamaAcara(),
            df.format(tiket.getHarga()),
            tiket.getTanggal(),
            tiket.getKategori(),
            tiket.getZona()
        };
        tableModel.addRow(rowData);
    } else {
        JOptionPane.showMessageDialog(this, "Data tidak ditemukan!", "Error", JOptionPane.INFORMATION_MESSAGE);
        // Hapus data di tabel jika data tidak ditemukan
        DefaultTableModel tableModel = (DefaultTableModel) tabel_kelola_tiket.getModel();
        tableModel.setRowCount(0);
    }
    }//GEN-LAST:event_button_searchActionPerformed

    private void button_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_refreshActionPerformed
        loadData();
    }//GEN-LAST:event_button_refreshActionPerformed

    private void menu_item_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_exitActionPerformed
        // TODO add your handling code here:
        dispose(); 
        new ViewFormDasboard(user).setVisible(true); // Open Login Form
    }//GEN-LAST:event_menu_item_exitActionPerformed

    private void text_Harga_TiketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_Harga_TiketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_Harga_TiketActionPerformed

    private void combo_kategori_tiketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_kategori_tiketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_kategori_tiketActionPerformed

    private void text_zona_tiketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_zona_tiketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_zona_tiketActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewFormTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewFormTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewFormTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewFormTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewFormTiket(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_Update;
    private javax.swing.JButton button_clear;
    private javax.swing.JButton button_create;
    private javax.swing.JButton button_delete;
    private javax.swing.JButton button_refresh;
    private javax.swing.JButton button_search;
    private javax.swing.JComboBox<String> combo_kategori_tiket;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenuItem menu_item_exit;
    private javax.swing.JTable tabel_kelola_tiket;
    private javax.swing.JTextField text_Harga_Tiket;
    private javax.swing.JTextField text_id;
    private javax.swing.JTextField text_namaAcara;
    private javax.swing.JTextField text_search;
    private javax.swing.JTextField text_tanggal;
    private javax.swing.JTextField text_zona_tiket;
    // End of variables declaration//GEN-END:variables

    private void loadData() {
    tiketCrudService = new TiketCrudServiceDbImpl(new ConnectionManager());
    List<T> listTiket = tiketCrudService.findAll(); // Mengambil semua data tiket
    Object[][] objectTiket = new Object[listTiket.size()][6];

    int counter = 0;

    for (T tiket : listTiket) {
        objectTiket[counter][0] = tiket.getId();
        objectTiket[counter][1] = tiket.getNamaAcara();
        objectTiket[counter][2] = df.format(tiket.getHarga());
        objectTiket[counter][3] = tiket.getTanggal();
        objectTiket[counter][4] = tiket.getKategori();
        objectTiket[counter][5] = tiket.getZona();
        counter++;
    }

    tabel_kelola_tiket.setModel(new javax.swing.table.DefaultTableModel(
        objectTiket,
        new String[]{
            "ID", "Nama Acara", "Harga Tiket", "Tanggal", "Kategori", "Zona"
        }
    ));
}

    private void emptyField() {
    text_id.setText("");
    text_namaAcara.setText("");
    text_Harga_Tiket.setText("");
    text_tanggal.setText("");
    combo_kategori_tiket.setSelectedIndex(0); // Reset ke index pertama
    text_zona_tiket.setText("");
}

    private static class T {

        private final int id;
        private final String namaAcara;
        private final double harga;
        private final String tanggal;
        private final String kategori;
        private final String zona;

    public T(int id, String namaAcara, double harga, String tanggal, String kategori, String zona) {
        this.id = id;
        this.namaAcara = namaAcara;
        this.harga = harga;
        this.tanggal = tanggal;
        this.kategori = kategori;
        this.zona = zona;
    }

    public int getId() {
        return id;
    }

    public String getNamaAcara() {
        return namaAcara;
    }

    public double getHarga() {
        return harga;
    }

    public String getTanggal() {
        return tanggal;
    }

    public String getKategori() {
        return kategori;
    }

    public String getZona() {
        return zona;
    }
    }
}
