/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.itenas.zoo.repository;

import org.itenas.zoo.model.User;

/**
 *
 * @author HP
 */

import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.itenas.zoo.model.Hewan;
import org.itenas.zoo.model.User;
import net.coobird.thumbnailator.Thumbnails;


public class ViewFormHewan extends javax.swing.JFrame {
    
    Boolean hasil;
    ControllerHewan conHewan = new ControllerHewan();
    private DefaultTableModel model;
    private final User user;

    /**
     * Creates new form ViewFormHewan
     */
    public ViewFormHewan() {
        initComponents();
        setLocationRelativeTo(null);
        model = new DefaultTableModel();

        tableHewan.setModel(model);

        model.addColumn("id");
        model.addColumn("nama");
        model.addColumn("spesies");
        model.addColumn("umur");
        getData();
        this.user = null;
    }
    
    public final void getData() {
        DefaultTableModel dtm = (DefaultTableModel) tableHewan.getModel();

        dtm.setRowCount(0);

        List<Hewan> listHewan = conHewan.showHewan();
        String[] data = new String[4];
        for (Hewan newHewan : listHewan) {
            data[0] = Integer.toString(newHewan.getId());
            data[1] = newHewan.getNama();
            data[2] = newHewan.getSpesies();
            data[3] = Integer.toString(newHewan.getUmur());
            dtm.addRow(data);
        }
    }
    
    public final void getDataSearch(String nama) {
        DefaultTableModel dtm = (DefaultTableModel) tableHewan.getModel();

        dtm.setRowCount(0);

        List<Hewan> listHewan = conHewan.searchHewan(nama);
        String[] data = new String[4];
        for (Hewan newHewan : listHewan) {
            data[0] = Integer.toString(newHewan.getId());
            data[1] = newHewan.getNama();
            data[2] = newHewan.getSpesies();
            data[3] = Integer.toString(newHewan.getUmur());
            dtm.addRow(data);
        }
    }
    
    public final void getDataUmursortedASC() {
        DefaultTableModel dtm = (DefaultTableModel) tableHewan.getModel();

        dtm.setRowCount(0);

        List<Hewan> listHewan = conHewan.sortHewanByUmurAsc();
        String[] data = new String[4];
        for (Hewan newHewan : listHewan) {
            data[0] = Integer.toString(newHewan.getId());
            data[1] = newHewan.getNama();
            data[2] = newHewan.getSpesies();
            data[3] = Integer.toString(newHewan.getUmur());
            dtm.addRow(data);
        }
    }
    
    public final void getDataUmursortedDESC() {
        DefaultTableModel dtm = (DefaultTableModel) tableHewan.getModel();

        dtm.setRowCount(0);

        List<Hewan> listHewan = conHewan.sortHewanByUmurDesc();
        String[] data = new String[4];
        for (Hewan newHewan : listHewan) {
            data[0] = Integer.toString(newHewan.getId());
            data[1] = newHewan.getNama();
            data[2] = newHewan.getSpesies();
            data[3] = Integer.toString(newHewan.getUmur());
            dtm.addRow(data);
        }
    }
    
    private void clearData() {
        txtnamahewan.setText("");
        txtspesies.setText("");
        txtumur.setText("");
        txtnamahewan.setEditable(true);
        txtspesies.setEditable(true);
        txtumur.setEditable(true);
        lbl_image.setIcon(null);
    }

    ViewFormHewan(User user) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.user = user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        SearchField = new javax.swing.JTextField();
        Search = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnclear = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableHewan = new javax.swing.JTable();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnsubmit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtumur = new javax.swing.JTextField();
        txtnamahewan = new javax.swing.JTextField();
        txtspesies = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        cbsorting = new javax.swing.JComboBox<>();
        image_pane = new javax.swing.JDesktopPane();
        lbl_image = new javax.swing.JLabel();
        btn_upload_image = new javax.swing.JButton();
        txt_image_path = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        combo_save_document = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menu_item_exit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 255, 0));

        jPanel2.setBackground(new java.awt.Color(255, 255, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("KELOLA DATA HEWAN");

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\TubesOOP\\Sikebi\\Sikebi\\src\\main\\java\\org\\itenas\\zoo\\repository\\image\\4669585.png")); // NOI18N
        jLabel4.setText("jLabel4");

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\TubesOOP\\Sikebi\\Sikebi\\src\\main\\java\\org\\itenas\\zoo\\repository\\image\\7027123.png")); // NOI18N
        jLabel7.setText("jLabel7");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 16, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addContainerGap())))
        );

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID");

        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });

        Search.setText("Search");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(200, 200, 200)
                .addComponent(SearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Search)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Search))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));
        jPanel4.setForeground(new java.awt.Color(60, 63, 65));

        btnclear.setBackground(new java.awt.Color(255, 255, 255));
        btnclear.setForeground(new java.awt.Color(0, 0, 0));
        btnclear.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\icon\\images\\clear.png")); // NOI18N
        btnclear.setText("CLEAR");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        tableHewan.setBackground(new java.awt.Color(255, 255, 255));
        tableHewan.setForeground(new java.awt.Color(0, 0, 0));
        tableHewan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id", "nama  hewan", "spesies", "umur"
            }
        ));
        tableHewan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableHewanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableHewan);

        jScrollPane2.setViewportView(jScrollPane1);

        btnupdate.setBackground(new java.awt.Color(255, 255, 255));
        btnupdate.setForeground(new java.awt.Color(0, 0, 0));
        btnupdate.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\icon\\images\\updated.png")); // NOI18N
        btnupdate.setText("UPDATE");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        btndelete.setBackground(new java.awt.Color(255, 255, 255));
        btndelete.setForeground(new java.awt.Color(0, 0, 0));
        btndelete.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\icon\\images\\delete.png")); // NOI18N
        btndelete.setText("DELETE");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnsubmit.setBackground(new java.awt.Color(255, 255, 255));
        btnsubmit.setForeground(new java.awt.Color(0, 0, 0));
        btnsubmit.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\icon\\images\\save.png")); // NOI18N
        btnsubmit.setText("SUBMIT");
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Umur");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Spesies");

        txtumur.setBackground(new java.awt.Color(0, 153, 153));
        txtumur.setForeground(new java.awt.Color(0, 0, 0));
        txtumur.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtumur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtumurActionPerformed(evt);
            }
        });

        txtnamahewan.setBackground(new java.awt.Color(0, 153, 153));
        txtnamahewan.setForeground(new java.awt.Color(0, 0, 0));
        txtnamahewan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtnamahewan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamahewanActionPerformed(evt);
            }
        });

        txtspesies.setBackground(new java.awt.Color(0, 153, 153));
        txtspesies.setForeground(new java.awt.Color(0, 0, 0));
        txtspesies.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtspesies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtspesiesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(btnclear)
                        .addGap(18, 18, 18)
                        .addComponent(btnupdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnsubmit)
                        .addGap(0, 11, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtumur)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnamahewan, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                            .addComponent(txtspesies)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtnamahewan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtspesies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtumur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        jPanel5.setBackground(new java.awt.Color(0, 153, 153));

        cbsorting.setForeground(new java.awt.Color(255, 255, 255));
        cbsorting.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Umur dari terkecil sampai terbesar", "Umur dari terbesar sampai terkecil" }));
        cbsorting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbsortingActionPerformed(evt);
            }
        });

        lbl_image.setForeground(new java.awt.Color(255, 255, 255));

        image_pane.setLayer(lbl_image, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout image_paneLayout = new javax.swing.GroupLayout(image_pane);
        image_pane.setLayout(image_paneLayout);
        image_paneLayout.setHorizontalGroup(
            image_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(image_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_image, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                .addContainerGap())
        );
        image_paneLayout.setVerticalGroup(
            image_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(image_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        btn_upload_image.setBackground(new java.awt.Color(255, 255, 255));
        btn_upload_image.setForeground(new java.awt.Color(0, 0, 0));
        btn_upload_image.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\icon\\images\\upload.png")); // NOI18N
        btn_upload_image.setText("UPLOAD");
        btn_upload_image.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_upload_imageActionPerformed(evt);
            }
        });

        txt_image_path.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_image_pathActionPerformed(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("IMAGE PATH");

        combo_save_document.setForeground(new java.awt.Color(255, 255, 255));
        combo_save_document.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Document", "Save to Word", "Save to PDF", "Save to Excel" }));
        combo_save_document.setMaximumSize(new java.awt.Dimension(107, 33));
        combo_save_document.setMinimumSize(new java.awt.Dimension(107, 33));
        combo_save_document.setPreferredSize(new java.awt.Dimension(107, 33));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbsorting, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_save_document, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txt_image_path)
                    .addComponent(btn_upload_image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)))
                .addGap(18, 18, 18)
                .addComponent(image_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbsorting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(btn_upload_image, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_image_path, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combo_save_document, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(image_pane)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 743, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jMenu1.setText("menu");

        menu_item_exit.setText("Exit");
        menu_item_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_exitActionPerformed(evt);
            }
        });
        jMenu1.add(menu_item_exit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableHewanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableHewanMouseClicked
        // TODO add your handling code here:
        int i = tableHewan.getSelectedRow();
        
        TableModel model = tableHewan.getModel();
        String namaHewan = model.getValueAt(i, 1).toString();
        String spesies = model.getValueAt(i, 1).toString();
        int umur = Integer.parseInt(model.getValueAt(i, 2).toString());
        txtnamahewan.setText(tableHewan.getValueAt(i, 1).toString());
        txtspesies.setText(tableHewan.getValueAt(i, 2).toString());
        txtumur.setText(tableHewan.getValueAt(i, 3).toString());
        
    try{
        File imageFile = new File("src/main/java/org/itenas/ooppraktikum/jdbc/images/" + namaHewan + ".jpeg");

        if (imageFile.exists()) {
            // Membaca file gambar
            BufferedImage originalImage = ImageIO.read(imageFile);

            // Mengubah ukuran gambar
            BufferedImage resizedImage = Thumbnails.of(originalImage)
                .size(230, 130)
                .asBufferedImage();

            // Menampilkan gambar pada JLabel
            ImageIcon icon = new ImageIcon(resizedImage);
            lbl_image.setIcon(icon);

            // (Opsional) Simpan gambar yang di-resize sebagai byte array
            ByteArrayOutputStream baos = new ByteArrayOutputStream();
            ImageIO.write(resizedImage, "jpeg", baos);
            byte[] imageBytes = baos.toByteArray();

            // (Opsional) Lakukan sesuatu dengan byte array imageBytes jika diperlukan
        } else {
            // Jika file gambar tidak ditemukan
            lbl_image.setIcon(null);
            JOptionPane.showMessageDialog(null, "Gambar tidak ditemukan untuk: " + namaHewan);
        }
    } catch (IOException e) {
        // Penanganan jika terjadi kesalahan saat membaca gambar
        lbl_image.setIcon(null);
        JOptionPane.showMessageDialog(null, "Error saat memuat gambar: " + e.getMessage());
    }
    }//GEN-LAST:event_tableHewanMouseClicked

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // TODO add your handling code here:
        clearData();
        getData();
    }//GEN-LAST:event_btnclearActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        int i = tableHewan.getSelectedRow();

        if (i == -1) {
            JOptionPane.showMessageDialog(btnupdate, "Harap pilih salah satu data", "warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int idMobil = Integer.parseInt(tableHewan.getModel().getValueAt(i, 0).toString());
        String oldNama = tableHewan.getModel().getValueAt(i, 1).toString();

        conHewan.updateHewan(txtnamahewan.getText(), oldNama , Integer.parseInt(txtumur.getText()), idMobil);
        JOptionPane.showMessageDialog(btnupdate, "Data berhasil diUpdate");
        getData();
        clearData();
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        int i =tableHewan.getSelectedRow();

    if (i == -1) {
        JOptionPane.showMessageDialog(btndelete, "Harap pilih salah satu data", "warning", JOptionPane.WARNING_MESSAGE);
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(btndelete, "Apakah Anda yakin ingin menghapus data ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
    if (confirm == JOptionPane.YES_OPTION) {
        
        int idHewan = Integer.parseInt(tableHewan.getModel().getValueAt(i, 0).toString());

        boolean isDeleted = conHewan.deleteHewan(idHewan);

        if (isDeleted) {
            JOptionPane.showMessageDialog(btndelete, "Data berhasil dihapus.");
            getData(); 
            clearData(); 
        } else {
            JOptionPane.showMessageDialog(btndelete, "Data gagal dihapus.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }          
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed
        // TODO add your handling code here:
        hasil = conHewan.insertHewan(txtnamahewan.getText(),txtspesies.getText(), Integer.parseInt(txtumur.getText()));
        if (hasil) {
            JOptionPane.showMessageDialog(null, "Data berhasil ditambahkan");
            getData();
            clearData();
        } else {
            JOptionPane.showMessageDialog(null, "Data gagal ditambahkan", " Pesan", JOptionPane.ERROR_MESSAGE);
        }
        
        String targetDirPath = "src/main/java/org/stenas/copprektskum/jdbc/images";
        File targetDir = new File(targetDirPath);

        if (!targetDir.exists()) {
            targetDir.mkdirs();
        }

        String fileName = txtnamahewan.getText().replaceAll("\\s+", "_") + ".Jpeg";
        File targetFile = new File(targetDir, fileName);

        try (OutputStream os = new FileOutputStream(targetFile)) {
            os.write(hewanImage); 
            JOptionPane.showMessageDialog(null, "File saved to: " + targetFile.getAbsolutePath());
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Error saving file: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnsubmitActionPerformed

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchActionPerformed

    private void txt_image_pathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_image_pathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_image_pathActionPerformed

    private void btn_upload_imageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_upload_imageActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser(); 
    String namaFileMobil = null; 
    ImageIcon mobilicon = null; 
    
    int returnValue = fileChooser.showOpenDialog(null); 
    
    if (returnValue == JFileChooser.APPROVE_OPTION) { 
        File file = fileChooser.getSelectedFile(); 
        namaFileMobil = file.getAbsolutePath(); 
        txt_image_path.setText(namaFileMobil); 
        
        try {
            File image = new File(namaFileMobil); 
            BufferedImage thumbnail = Thumbnails.of(image) 
                                              .size(180, 220)
                                              .asBufferedImage();
            
            
            ByteArrayOutputStream os = new ByteArrayOutputStream();
            ImageIO.write(thumbnail, "jpeg", os); 
            InputStream is = new ByteArrayInputStream(os.toByteArray()); 
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte[] buf = new byte[1024];
            
            for (int readNum; (readNum = is.read(buf)) != -1;) { 
                bos.write(buf, 0, readNum); 
            }
           
            mobilicon = new ImageIcon(thumbnail); 
            lbl_image.setIcon(mobilicon);
            
            hewanImage = bos.toByteArray(); 
            
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Error processing image: " + e.getMessage());
        }
    } else {
        JOptionPane.showMessageDialog(null, "No file selected.");}
    }//GEN-LAST:event_btn_upload_imageActionPerformed

    private void cbsortingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbsortingActionPerformed
        // TODO add your handling code here:
        switch (cbsorting.getSelectedIndex()) {
            case 0:
                getDataUmursortedASC();
                break;
            case 1:
                getDataUmursortedDESC();
                break;
            default:
                getData();
                break;
        }
        
    }//GEN-LAST:event_cbsortingActionPerformed

    private void menu_item_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_item_exitActionPerformed
        // TODO add your handling code here:
        dispose(); 
        new ViewFormDasboard(user).setVisible(true); // Open Login Form
    }//GEN-LAST:event_menu_item_exitActionPerformed

    private void txtnamahewanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamahewanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamahewanActionPerformed

    private void txtspesiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtspesiesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtspesiesActionPerformed

    private void txtumurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtumurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtumurActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewFormHewan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewFormHewan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewFormHewan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewFormHewan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new ViewFormHewan().setVisible(true); // Pastikan frame diatur menjadi terlihat
              }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Search;
    private javax.swing.JTextField SearchField;
    private javax.swing.JButton btn_upload_image;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnsubmit;
    private javax.swing.JButton btnupdate;
    private javax.swing.JComboBox<String> cbsorting;
    private javax.swing.JComboBox<String> combo_save_document;
    private javax.swing.JDesktopPane image_pane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_image;
    private javax.swing.JMenuItem menu_item_exit;
    private javax.swing.JTable tableHewan;
    private javax.swing.JTextField txt_image_path;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnamahewan;
    private javax.swing.JTextField txtspesies;
    private javax.swing.JTextField txtumur;
    // End of variables declaration//GEN-END:variables
    byte[] hewanImage = null;
}

